---
title: "Overzicht laatste weken"
author: "Aart Dijkstra"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 6
    toc_float: true
---

```{css echo=F}
table {
  border: 0;
}

th {
  padding: 3px;
}

td {
  padding: 3px;
}
```

```{r setup, include=F}
knitr::opts_chunk$set(warning=F)
```


```{r echo=F}
suppressPackageStartupMessages(library(tidyverse))
library(lubridate)
library(plotly)
library(DBI)
library(odbc)
library(glue)
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(sf))
library(leaflet)
library(htmltools)
library(xtable)

options(xtable.comment = FALSE,
        xtable.type="html",
        xtable.html.table.attributes="border=0")

printf = function (...) cat(paste(sprintf(...),"\n"))

# GGD NOG kleuren
nog_colors = c("#1D1756", "#D1005D", "#2F6594", "#D3DFF1", "#FFBDDB")
nog_palette = c("#FAE6EF","#F6CCDF","#ED99BE","#E3669E","#D1005D")

kaartdata = st_read("../../../Documenten - NOG NOG W Openbare data/Kaarten/pc4_arcgis.shp")

conn = dbConnect(odbc::odbc(), Driver="SQL Server", Server="az-odb0\\odbnog", uid="HPZone", pwd="%16IZB01d7@", Database="HPZone")

freq.table = function (..., is.list=F, is.table=F, row.prop=T, col.prop=T) {
  if (is.table) {
    result = as_tibble(...)
    
    # eerste kolom wordt rijnamen, daarna omzetten naar matrix
    tmp = result
    result = as.matrix(result[,-1])
    rownames(result) = as.character(tmp[[1]])
  } else if (is.list) {
    vars = list(...)
    full.set = lapply(vars, freq.table)
    names(full.set) = sapply(..., deparse)
    
    return(full.set)
  }
  else result = table(...)
  if (all(dim(result) == 0)) return(data.frame(NA))
  ret = result
  if (length(dim(result)) == 1) {
    # geen rijen of kolommen, alleen een lijst
    prop = proportions(result)*100
    tmp = as.data.frame(matrix(nrow = length(ret)+1, ncol=2))
    tmp[1:(nrow(tmp)-1),seq(from=1,to=ncol(tmp)-1,by=2)] = ret
    tmp[1:(nrow(tmp)-1),seq(from=2,to=ncol(tmp),by=2)] = sprintf("%.2f%%", prop)
    ret = tmp
    ret[nrow(ret),1] = sum(ret[,1], na.rm=T)
    rownames(ret) = c(names(result), "Totaal")
    colnames(ret) = c("n", "Perc")
    return(ret)
  }
  
  # totalen bewaren voor later
  totals.row = rowSums(ret)
  totals.col = colSums(ret)
  
  if (row.prop) {
    prop = proportions(result, margin=2)*100
    tmp = as.data.frame(matrix(nrow = (nrow(result)*2)+1, ncol=ncol(ret)))
    tmp[seq(from=1,to=nrow(tmp)-2,by=2),] = ret
    tmp[seq(from=2,to=nrow(tmp)-1,by=2),] = sprintf("%.2f%%", prop)
    ret = tmp
  }
  if (col.prop) {
    prop = proportions(result, margin=1)*100
    tmp = as.data.frame(matrix(nrow = nrow(ret), ncol=(ncol(ret)*2)+1))
    tmp[,seq(from=1,to=ncol(tmp)-1,by=2)] = ret
    if (row.prop) {
      # als hierboven rijen zijn ingevoegd moeten die rijen worden overgeslagen
      # bij het invoeren van de nieuwe waardes
      # praktisch betekent dit een lege regel tussen iedere waarde
      tmp[seq(from=1,to=nrow(tmp)-1,by=2),seq(from=2,to=ncol(tmp),by=2)] = sprintf("%.2f%%", prop)
    }
    else {
      tmp[,seq(from=2,to=ncol(tmp)-1,by=2)] = sprintf("%.2f%%", prop)
    }
    ret = tmp
  }
  
  # col-/rownames pas aan het einde toevoegen; bij het aanmaken van tmp gaan die
  # telkens verloren
  if (row.prop) {
    rownames(ret) = sprintf("tmp%d", 1:nrow(ret))
    rownames(ret)[seq(from=1,to=nrow(ret)-2,by=2)] = rownames(result)
    rownames(ret)[seq(from=2,to=nrow(ret)-1,by=2)] = sprintf("P%d", 1:(nrow(ret)/2))
  }
  else {
    rownames(ret) = rownames(result)
  }
  if (col.prop) {
    colnames(ret)[seq(from=1,to=ncol(ret)-2,by=2)] = colnames(result)
    colnames(ret)[seq(from=2,to=ncol(ret)-1,by=2)] = sprintf("P%d", 1:(ncol(ret)/2))
  }
  else {
    colnames(ret) = colnames(result)
  }
  
  # totalen toevoegen
  ret[nrow(ret),seq(from=1,to=ncol(ret)-1,by=2)] = totals.col
  ret[nrow(ret),seq(from=2,to=ncol(ret)-1,by=2)] = sprintf("%.2f%%", proportions(totals.col)*100)
  rownames(ret)[nrow(ret)] = "Totaal"
  ret[seq(from=1,to=nrow(ret)-1,by=2),ncol(ret)] = totals.row
  ret[seq(from=2,to=nrow(ret)-1,by=2),ncol(ret)] = sprintf("%.2f%%", proportions(totals.row)*100)
  colnames(ret)[ncol(ret)] = "Totaal"
  
  test = suppressWarnings(chisq.test(result))
  
  ret[nrow(ret),ncol(ret)] = sprintf("p = %0.3e", test$p.value)
  
  return(ret)
}
```

```{r}
startdatum = floor_date(Sys.Date() - dweeks(6), unit="week")
printf("Begindatum: %s (week %d)", startdatum, week(startdatum))
```


# Overzicht casuïstiek in de laatste 6 weken
```{sql connection=conn, output.var="cases"}
SELECT * FROM vw_cases WHERE peildatum >= ?startdatum
```

```{r echo=F}
# om onduidelijke redenen interpreteert R de data niet direct als data
cases$peildatum = as.Date(cases$peildatum)
cases$melddatum = as.Date(cases$melddatum)
```


```{r}
ggplotly(ggplot(cases, aes(y=groep, fill=diagnosezekerheid)) +
  geom_bar() +
  labs(x="Aantal", y="Infectie", title="Aantal gemelde gevallen", fill="Zekerheid"))
```

```{r}
ggplotly(ggplot(cases %>% filter(diagnosezekerheid != "Discarded"), aes(x=peildatum, fill=groep)) +
  geom_bar() +
  labs(x="Datum", y="Aantal", title="Aantal gemelde gevallen", fill="Infectie"))
```

## Overzicht per groep
```{r}
infecties = unique(cases$groep)
infecties_sql = glue_sql("{infecties*}", .con=conn)
beginjaar = year(startdatum) - 5
```

```{sql connection=conn, output.var="cases.historisch"}
SELECT YEAR(peildatum) as jaar, MONTH(peildatum) AS maand, groep, COUNT(hpzone_id) AS n FROM vw_cases
WHERE infectie_groep IN (?infecties_sql) AND YEAR(peildatum) >= ?beginjaar AND diagnosezekerheid != 'Discarded'
GROUP BY YEAR(peildatum), MONTH(peildatum), groep
```

```{r results="asis"}
for (inf in infecties) {
  cat("### ", inf, "\n")
  cat("#### Leeftijd en geslacht\n")
  print(ggplot(cases %>% filter(groep == inf), aes(x=leeftijd, fill=geslacht)) +
    geom_bar() +
    labs(x="Leeftijd", y="Aantal", fill="Geslacht", title="Demografie patienten ", subtitle=inf))
  cat("\n\nLeeftijd:\n")
  print(xtable(t(summary(cases$leeftijd[which(cases$groep == inf)]))))
  cat("\nGeslacht:\n")
  print(xtable(freq.table(cases$geslacht[which(cases$groep == inf)])))
  cat("\n\n")
  cat("#### Verloop meldingen afgelopen tijd\n")
  print(ggplot(cases %>% filter(groep == inf), aes(x=peildatum, fill=diagnosezekerheid)) +
    geom_bar() +
    labs(x="Datum", y="Aantal", fill="Zekerheid", title="Aantal meldingen in de laatste 6 weken", subtitle=inf) +
    scale_x_date(limits=c(startdatum, Sys.Date())))
  cat("\n\nLaatste melding: ", strftime(max(cases$peildatum[cases$groep == inf], na.rm=T), "%Y-%m-%d"), "\n\n")
  cat("#### Verloop door de jaren\n")
  print(ggplot(cases.historisch %>% filter(groep == inf), aes(x=maand, y=n)) +
    geom_smooth() +
    geom_col(aes(fill=factor(jaar)), position="dodge") +
    labs(title="Verloop meldingen over tijd", subtitle=inf, x="Maand", y="Aantal", fill="Jaar") +
    scale_x_continuous(breaks=c(1, 3, 5, 7, 9, 11), labels=c("Jan", "Maart", "Mei", "Juli", "Sept", "Nov"), limits=c(0, 13)))
  cat("\n")
  print(xtable(cases.historisch %>% filter(groep == inf) %>% group_by(jaar) %>% summarize(n=sum(n))))
  cat("\n\n")
}
```

## Context en demografie
```{r fig.width=10}
ggplot(cases, aes(x=leeftijd, fill=geslacht)) +
  geom_bar() +
  facet_wrap(vars(groep)) +
  labs(x="Leeftijd", y="Aantal", fill="Geslacht", title="Demografie patienten")
```

```{r}
datatable(freq.table(cases$groep, cases$geslacht))
freq.table(cases$meldorganisatie)
```

```{r}
ggplotly(ggplot(cases %>% filter(diagnosezekerheid != "Discarded"), aes(y=groep, fill=meldorganisatie)) +
  geom_bar() +
  labs(x="Aantal", y="Infectie", fill="Melder", title="Meldingen per organisatie"))
```


# Overzicht situations in de laatste weken
```{sql connection=conn, output.var="situations"}
SELECT * FROM vw_situations WHERE datum >= ?startdatum
```

```{r}
ggplotly(ggplot(situations, aes(y=agent, fill=zekerheid)) +
  geom_bar() +
  labs(x="Aantal", y="Verwekker", title="Aantal gemelde uitbraken", fill="Zekerheid"))
```

```{r}
ggplotly(ggplot(situations, aes(x=datum, fill=agent)) +
  geom_bar() +
  labs(x="Datum", y="Aantal", title="Aantal gemelde uitbraken", fill="Zekerheid"))
```

```{r}
ggplotly(ggplot(situations, aes(y=scenario, fill=agent)) +
  geom_bar() +
  labs(x="Aantal", y="Type", title="Aantal gemelde uitbraken", fill="Verwekker"))
```

## Vergelijking met eerdere jaren
```{r}
agents = unique(situations$agent)
agent_sql = glue_sql("{agents*}", .con=conn)
beginjaar = year(startdatum) - 5
```

```{sql connection=conn, output.var="situations.historisch"}
SELECT YEAR(datum) as jaar, MONTH(datum) AS maand, agent, COUNT(hpzone_id) AS n FROM vw_situations
WHERE agent IN (?agent_sql) AND YEAR(datum) >= ?beginjaar
GROUP BY YEAR(datum), MONTH(datum), agent
```

```{r results="asis"}
for (ag in agents) {
  cat("### ", ag, "\n")
  suppressWarnings(print(ggplot(situations.historisch %>% filter(agent == ag), aes(x=maand, y=n)) +
    geom_smooth() +
    geom_col(aes(fill=factor(jaar)), position="dodge") +
    labs(title=ag, x="Maand", y="Aantal", fill="Jaar") +
    scale_x_continuous(breaks=c(1, 3, 5, 7, 9, 11), labels=c("Jan", "Maart", "Mei", "Juli", "Sept", "Nov"), limits=c(0, 13))))
}
```

## Context, artikel 26, en risiconiveau
```{r}
freq.table(situations$context)
datatable(freq.table(situations$agent, situations$artikel26))
freq.table(situations$risiconiveau)
```


# Overzicht enquiries in de laatste weken
```{sql connection=conn, output.var="enquiries"}
SELECT * FROM vw_enquiries WHERE startdatum >= ?startdatum
```

```{r}
enquiries = enquiries %>%
  mutate(across(startdatum:einddatum, ~as.Date(.x)))
```


```{r}
ggplotly(ggplot(enquiries, aes(y=onderwerp, fill=typebeller)) +
  geom_bar() +
  labs(x="Aantal", y="Onderwerp", title="Aantal telefonische vragen", fill="Type beller"))
```

```{r}
ggplotly(ggplot(enquiries, aes(x=startdatum, fill=onderwerp)) +
  geom_bar() +
  labs(x="Aantal", y="Type", title="Aantal telefonische vragen", fill="Verwekker"))
```

## Vergelijking met eerdere jaren
```{r}
onderwerpen = unique(enquiries$onderwerp)
onderwerpen_sql = glue_sql("{onderwerpen*}", .con=conn)
beginjaar = year(startdatum) - 5
```

```{sql connection=conn, output.var="enquiries.historisch"}
SELECT YEAR(startdatum) as jaar, MONTH(startdatum) AS maand, onderwerp, COUNT(hpzone_id) AS n FROM vw_enquiries
WHERE onderwerp IN (?onderwerpen_sql) AND YEAR(startdatum) >= ?beginjaar
GROUP BY YEAR(startdatum), MONTH(startdatum), onderwerp
```

```{r results="asis"}
for (ond in onderwerpen) {
  cat("### ", ond, "\n")
  suppressWarnings(print(ggplot(enquiries.historisch %>% filter(onderwerp == ond), aes(x=maand, y=n)) +
    geom_smooth() +
    geom_col(aes(fill=factor(jaar)), position="dodge") +
    labs(title=ond, x="Maand", y="Aantal", fill="Jaar") +
    scale_x_continuous(breaks=c(1, 3, 5, 7, 9, 11), labels=c("Jan", "Maart", "Mei", "Juli", "Sept", "Nov"), limits=c(0, 13))))
}
```

## Demografie bellers
```{r}
freq.table(enquiries$typebeller, enquiries$geslacht)
freq.table(enquiries$onderwerp, enquiries$status)
```


# Geografische spreiding
```{r fig.width=12}
casespalette = colorFactor("Set1", cases$groep)

inf_groepen = sort(unique(cases$groep))

kaart = leaflet() %>%
  addTiles()

# geen idee wat dit doet, maar het voorkomt een fout
# zie https://github.com/r-spatial/sf/issues/1762 en https://github.com/r-spatial/sf/issues/1771
sf_use_s2(FALSE)

for (inf_groep in inf_groepen) {
  inf_cases = cases %>%
    filter(groep == inf_groep)
  if (all(is.na(inf_cases$postcode))) next
  inf_cases = inf_cases %>%
    mutate(postcode=as.character(postcode),
           popup=sprintf("%s%d - %s (%s) - %s (%s)<br />Peildatum: %s<br />Melddatum: %s<br />OSIRIS: %s (%s)",
                         geslacht, leeftijd, postcode, gemeentenaam, infectie, groep, peildatum, melddatum, statusmelding, melddatum)) %>%
    arrange(desc(peildatum)) %>%
    group_by(groep, postcode) %>%
    summarize(n=n(), popup=str_c(popup, collapse="<hr />")) %>%
    mutate(label=sprintf("%s - %s - %d gevallen", postcode, groep, n))
    
  kaart = kaart %>%
    addCircleMarkers(data=suppressWarnings(kaartdata %>% right_join(inf_cases, by=c("PC4"="postcode")) %>%
                       st_centroid()),
                     radius=~n*3,
                     color=~casespalette(inf_groep),
                     opacity=0.8,
                     label=~label,
                     popup=~popup,
                     group=inf_groep)
}

kaart %>%
  addLayersControl(overlayGroups=inf_groepen)
```

```{r}
agents = unique(c(situations$agent_groep, situations$agent[is.na(situations$agent_groep)]))

agentspalette = colorFactor("Set1", agents)

kaart = leaflet() %>%
  addTiles()

for (ag in agents) {
  inf_situations = situations %>%
    filter(agent == ag | agent_groep == ag)
  if (all(is.na(inf_situations$postcode))) next
  inf_situations = inf_situations %>%
    mutate(postcode=as.character(postcode),
           popup=sprintf("%s (%s) - %s (%s)<br />Peildatum: %s<br />Type: %s (%s)<br />Artikel 26: %s",
                         postcode, gemeentenaam, agent, agent_groep, datum, type, status, ifelse(artikel26 == 1, "ja", "nee"))) %>%
    arrange(desc(datum)) %>%
    group_by(agent, postcode) %>%
    summarize(n=n(), popup=str_c(popup, collapse="<hr />")) %>%
    mutate(label=sprintf("%s - %s - %d gevallen", postcode, agent, n))
    
  kaart = kaart %>%
    addCircleMarkers(data=suppressWarnings(kaartdata %>% right_join(inf_situations, by=c("PC4"="postcode")) %>%
                       st_centroid()),
                     radius=~n*3,
                     color=~agentspalette(ag),
                     opacity=0.8,
                     label=~label,
                     popup=~popup,
                     group=ag)
}

kaart %>%
  addLayersControl(overlayGroups=agents)
```

# Data Nivel peilstations
```{r echo=F}
conn.nivel = dbConnect(odbc::odbc(), Driver="SQL Server", Server="az-odb0\\odbnog", Database="ODBNOG")
```

```{r}
# omdat data van het Nivel per week gaat moeten we soms omrekenen; in week 2 moeten de laatste 4 weken van vorig jaar ook hebben
startweek1 = week(startdatum)
startjaar1 = year(startdatum)
startweek2 = week(startdatum)
startjaar2 = year(startdatum)
if (startjaar1 < year(Sys.Date())) {
  startweek2 = 1
  startjaar2 = year(Sys.Date())
}
```

```{sql connection=conn.nivel, output.var="niveldata"}
SELECT nivel_zorgregistraties.*, ggd.ggd_naam FROM nivel_zorgregistraties
INNER JOIN ggd ON ggd.ggd_id = nivel_zorgregistraties.ggd_regio
WHERE ((jaar = ?startjaar1 AND week >= ?startweek1)
  OR (jaar = ?startjaar2 AND week >= ?startweek2))
  AND ggd_regio IN (4, 5, 6, 7, 8, 100)
```

```{r}
niveldata$weektekst = sprintf("%d-%02.0f", niveldata$jaar, niveldata$week)
weken = unique(niveldata$weektekst)
volgorde = order(weken)
weeknummers = data.frame(weektekst=weken, weeknummer=volgorde)
niveldata = niveldata %>%
  left_join(weeknummers, by="weektekst")
```


```{r}
# alleen aandoeningen waarvan er tenminste één meting boven het landelijke gemiddelde ligt
aandoeningen = unique(niveldata$aandoening[niveldata$prevalentie_ratio > 1.0])
for (a in aandoeningen) {
  data = niveldata[niveldata$aandoening == a,]
  
  plot(data$weeknummer[data$ggd_regio == 6], data$per100k[data$ggd_regio == 6], col=nog_colors[1], type="l", lwd=2,
       main=a, ylab="Incidentie per 100.000", xlab=NA, axes=F,
       ylim=c(min(data$per100k, na.rm=T), max(data$per100k, na.rm=T)))
  grid(nx=NA, ny=NULL)
  par(new=T)
  plot(data$weeknummer[data$ggd_regio == 6], data$per100k[data$ggd_regio == 6], col=nog_colors[1], type="l", lwd=2,
       main=a, ylab="Incidentie per 100.000", xlab=NA, axes=F,
       ylim=c(min(data$per100k, na.rm=T), max(data$per100k, na.rm=T)))
  axis(1, at=weeknummers$weeknummer, labels=weeknummers$weektekst)
  axis(2, at=pretty(data$per100k))
  for (i in 1:4) {
    regio = c(4, 5, 7, 8)[i]
    lines(data$weeknummer[data$ggd_regio == regio], data$per100k[data$ggd_regio == regio], col=nog_colors[i + 1])
  }
  lines(data$weeknummer[data$ggd_regio == 100], data$per100k[data$ggd_regio == 100], col="black", lty="dashed")
  par(new=T)
  plot(0, 0, type="n", axes=F, main=NA, xlab=NA, ylab=NA)
  legend("bottom", c("NOG", "IJsselland", "Twente", "G-M", "G-Z", "NL"), col=c(nog_colors, "black"), lwd=c(2, rep(1, 5)), lty=c(rep("solid", 5), "dashed"),
         horiz=T, xpd=T, inset=c(0, -0.30), cex=0.8)
  
  # print(ggplot(niveldata %>% filter(aandoening == a), aes(x=weeknummer, y=per100k, col=ggd_naam)) +
  #   geom_line() +
  #   scale_x_continuous(breaks=weeknummers$weeknummer, labels=weeknummers$weektekst) +
  #   labs(x="Week", y="Incidentie per 100.000", title=a) +
  #   theme(legend.position="bottom",
  #         axis.text.x=element_text(angle=90, vjust = 0.5, hjust=1)))
}
```

